"""
Django settings for tes project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

"""


import os # load the os module
from pathlib import Path # load the path
from dotenv import load_dotenv # load the dotenv

load_dotenv() 

BASE_DIR = Path(__file__).resolve().parent.parent # getting the dir from the productio na dnthe dvlopemenr 

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-change-me-in-production") # secturt key used for the https i think 

DEBUG = os.environ.get("DEBUG", "False") == "True" # why is it true 

ALLOWED_HOSTS = ["*"] # no issue since im at the testing 


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin" , # for creating and manage the users
    "django.contrib.auth" , # controlling the usets
    "django.contrib.contenttypes" , # for genric refrence to the db 
    "django.contrib.sessions" , # for manageing the sessions  
    "django.contrib.messages" , # for sending the messages to the users 
    "django.contrib.staticfiles" , # fir servingt he static files to theclint (is it include the temolate too )
    "cloudinary_storage" ,
    "cloudinary" ,
    "accounts" ,
    "core" ,
    "products" ,
    "cart" ,
    "orders" ,
    "reviews" ,
    "tailwind" ,
    "theme" ,
]




MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware", # secuirty middle ware for handling http->https convertion
    "whitenoise.middleware.WhiteNoiseMiddleware", # for serviceing the sttac file on the production 
    "django.contrib.sessions.middleware.SessionMiddleware", # session handler 
    "django.middleware.common.CommonMiddleware",  #utitlity middle ware 
    "django.middleware.csrf.CsrfViewMiddleware", # for validating each of the request 
    "django.contrib.auth.middleware.AuthenticationMiddleware", #for auth 
    "django.contrib.messages.middleware.MessageMiddleware", # for messages 
    "django.middleware.clickjacking.XFrameOptionsMiddleware", # for making sure i can't add this web inside a another web 
] # now my question does the order in which we do the middleware cause any issue 



# for managignt he main urs
ROOT_URLCONF = "tes.urls"



# what does this do 
# this does the following that  is this tells the django where to find the templates 
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates" ,
        "DIRS": [BASE_DIR / "templates"] ,# tell to look inside the templates ininside each of the folder
        "APP_DIRS": True , # tell to look inside the templates ininside each of the folder
        "OPTIONS": { # what dara are injectted to each of the temolated by default 
            "context_processors": [
                "django.template.context_processors.request" ,
                "django.contrib.auth.context_processors.auth" ,
                "django.contrib.messages.context_processors.messages" ,
                "cart.cart.cart_context" ,
            ] ,
        } ,
    } ,
]

# for tellin which applcaion are we using 
WSGI_APPLICATION = "tes.wsgi.application"



import dj_database_url 

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

else:
    # Fallback to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# session engine + other things 
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Django 6.0-compatible storage configuration
# Cloudinary handles media (uploaded files), WhiteNoise handles static files
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# UPI Payment Configuration
UPI_ID = os.environ.get("UPI_ID", "gpzstore@oksbi")
PAYEE_NAME = os.environ.get("PAYEE_NAME", "GPZ Store")

# Google Sheets Sync — Apps Script Web App URL
GOOGLE_SCRIPT_URL = os.environ.get("GOOGLE_SCRIPT_URL", "")

# Cloudinary — Cloud Storage for uploaded files (fixes Vercel read-only filesystem)
# django-cloudinary-storage reads CLOUDINARY_URL from the environment automatically

CART_SESSION_ID = "cart"

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

JAZZMIN_SETTINGS = {
    "site_title": "tes Admin",
    "site_header": "tes",
    "site_brand": "tes",
    "welcome_sign": "Welcome to tes Management",
    "copyright": "tes Ltd",
    "search_model": ["auth.User", "products.Product"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["auth", "products", "orders", "cart"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "products.Product": "fas fa-box",
        "products.Category": "fas fa-tags",
        "orders.Order": "fas fa-shopping-cart",
        "cart.Cart": "fas fa-trash",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "pulse",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
