"""
Django settings for Vajra project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

"""


import os # load the os module
from pathlib import Path # load the path
from dotenv import load_dotenv # load the dotenv

load_dotenv() 

BASE_DIR = Path(__file__).resolve().parent.parent # getting the dir from the productio na dnthe dvlopemenr 

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-change-me-in-production") # secturt key used for the https i think 

DEBUG = os.environ.get("DEBUG", "False") == "True" # why is it true 

ALLOWED_HOSTS = ["*"] # no issue since im at the testing 


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin" , # for creating and manage the users
    "django.contrib.auth" , # controlling the usets
    "django.contrib.contenttypes" , # for genric refrence to the db 
    "django.contrib.sessions" , # for manageing the sessions  
    "django.contrib.messages" , # for sending the messages to the users 
    "django.contrib.staticfiles" , # fir servingt he static files to theclint (is it include the temolate too )
    "accounts" ,
    "core" ,
    "products" ,
    "cart" ,
    "orders" ,
    "reviews" ,
]




MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware", # secuirty middle ware for handling http->https convertion
    "whitenoise.middleware.WhiteNoiseMiddleware", # for serviceing the sttac file on the production 
    "django.contrib.sessions.middleware.SessionMiddleware", # session handler 
    "django.middleware.common.CommonMiddleware",  #utitlity middle ware 
    "django.middleware.csrf.CsrfViewMiddleware", # for validating each of the request 
    "django.contrib.auth.middleware.AuthenticationMiddleware", #for auth 
    "django.contrib.messages.middleware.MessageMiddleware", # for messages 
    "django.middleware.clickjacking.XFrameOptionsMiddleware", # for making sure i can't add this web inside a another web 
] # now my question does the order in which we do the middleware cause any issue 



# for managignt he main urs
ROOT_URLCONF = "Vajra.urls"



# what does this do 
# this does the following that  is this tells the django where to find the templates 
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates" ,
        "DIRS": [BASE_DIR / "templates"] ,# tell to look inside the templates ininside each of the folder
        "APP_DIRS": True , # tell to look inside the templates ininside each of the folder
        "OPTIONS": { # what dara are injectted to each of the temolated by default 
            "context_processors": [
                "django.template.context_processors.request" ,
                "django.contrib.auth.context_processors.auth" ,
                "django.contrib.messages.context_processors.messages" ,
                "cart.cart.cart_context" ,
            ] ,
        } ,
    } ,
]

# for tellin which applcaion are we using 
WSGI_APPLICATION = "Vajra.wsgi.application"



import dj_database_url 

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

else:
    # Fallback to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# session engine + other things 
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

CART_SESSION_ID = "cart"
