# Generated by Django 6.0.3 on 2026-04-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_is_paid_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
        migrations.AddField(
            model_name="order",
            name="utr_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
