# Generated by Django 6.0.3 on 2026-04-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_signature",
        ),
        migrations.AddField(
            model_name="order",
            name="stock_deducted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("upi_qr", "UPI QR")], default="upi_qr", max_length=50
            ),
        ),
    ]
