# Generated by Django 6.0.3 on 2026-04-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="is_available",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="stock_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("In Stock", "In Stock"),
                    ("Out of Stock", "Out of Stock"),
                    ("Pre-Order", "Pre-Order"),
                    ("Discontinued", "Discontinued"),
                ],
                default="In Stock",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
        migrations.AddField(
            model_name="product",
            name="image_gallery",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of image URLs for the product gallery.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="long_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="model_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Key-value pairs of product specs e.g. {RAM: 8GB, Display: 6.1 inch}",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.tag"
            ),
        ),
    ]
